import Head from "next/head";
import styles from "../styles/Home.module.css";
import { SubmitHandler, useForm } from "react-hook-form";
import { useEffect, useState } from "react";
import FileInput from "../components/FileInput";
import { ChakraProvider, Container } from "@chakra-ui/react";
import Header from "../components/Header";
import Body from "../components/Body";
import OverlapCalcContainer from "../components/OverlapCalcContainer";

export default function Home() {
  return (
    <ChakraProvider>
      <Head>
        <title>ETF Overlap Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Body>
        <OverlapCalcContainer />
      </Body>
    </ChakraProvider>
  );
}
